apiVersion: v1
kind: Pod
metadata:
  name: pvc-populator
spec:
  containers:
  - name: pvc-populator
    image: busybox
    command: ["sleep", "3600"]
    volumeMounts:
    - name: model-volume
      mountPath: /model_files
  volumes:
  - name: model-volume
    persistentVolumeClaim:
      claimName: model-pvc
  restartPolicy: Never

